"""Email templates supported by the mailer."""

from enum import StrEnum


class EmailTemplate(StrEnum):
    OWNER_REGISTER_OTP = "OWNER_REGISTER_OTP"
    OWNER_RESET_PASSWORD_OTP = "OWNER_RESET_PASSWORD_OTP"
    ORGANIZATION_REGISTER_OTP = "ORGANIZATION_REGISTER_OTP"
    ORGANIZATION_RESET_PASSWORD_OTP = "ORGANIZATION_RESET_PASSWORD_OTP"
