"""Email templates supported by the mailer."""

from enum import StrEnum


class EmailTemplate(StrEnum):
    OWNER_REGISTER_OTP = "OWNER_REGISTER_OTP"
    OWNER_RESET_PASSWORD_OTP = "OWNER_RESET_PASSWORD_OTP"
    OWNER_LOGIN_OTP = "OWNER_LOGIN_OTP"
    ORGANIZATION_REGISTER_OTP = "ORGANIZATION_REGISTER_OTP"
    ORGANIZATION_RESET_PASSWORD_OTP = "ORGANIZATION_RESET_PASSWORD_OTP"
    ORGANIZATION_LOGIN_OTP = "ORGANIZATION_LOGIN_OTP"
    ISSUER_APPLICATION_RECEIVED = "ISSUER_APPLICATION_RECEIVED"
    VERIFIER_APPLICATION_RECEIVED = "VERIFIER_APPLICATION_RECEIVED"
    INSTITUTION_INVITE = "INSTITUTION_INVITE"
    APPLICATION_REJECTED = "APPLICATION_REJECTED"
