APP_NAME: "Lucidex API (Staging)"
ENV: "staging"
API_V1_PREFIX: "/api/v1"
MONGODB_DB_NAME: "lucidex_staging"
CORS_ALLOWED_ORIGINS: "http://localhost:5173"
EKYC_MOCK_MODE: "true"
FRONTEND_MOBILE_CAPTURE_BASE_URL: "http://localhost:5173/mobile-capture"